deployment:
  tasks:
    - export DEPLOYPATH=/home/wastemecc2/repositories/waste/waste_back
    - /bin/cp -R $DEPLOYPATH/public/build/ /home/wastemecc2/public_html/build/
    - cd $DEPLOYPATH
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
