deployment:
  tasks:
    - export DEPLOYPATH=/home/wastemecc2/repositories/waste/waste_back
    - export DEPLOYPATH_MOBILE=/home/wastemecc2/repositories/waste/waste_pwa1/
    - /bin/cp -Rf $DEPLOYPATH/public/build /home/wastemecc2/public_html/
    - cd $DEPLOYPATH
    # - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    # - php artisan migrate:fresh --seed --force
    - cd $DEPLOYPATH_MOBILE
    # - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - /bin/cp -Rf $DEPLOYPATH_MOBILE/public/build /home/wastemecc2/public_html/mobile/
    
    
