deployment:
  tasks:
    - export DEPLOYPATH=/home/wastemecc2/repositories/waste/waste_back
    - /bin/cp -Rf $DEPLOYPATH/public/build /home/wastemecc2/public_html/
    # - cd $DEPLOYPATH
    # - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    # - php artisan migrate:fresh --seed --force