<?php

namespace Database\Seeders;

use App\Models\AimagCity;
use App\Models\SoumDistrict;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AimagSoumDistictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        AimagCity::create(["id" => 1, 'code' => '65', 'name' => 'Архангай']);
        AimagCity::create(["id" => 2, 'code' => '83', 'name' => 'Баян-Өлгий']);
        AimagCity::create(["id" => 3, 'code' => '64', 'name' => 'Баянхонгор']);
        AimagCity::create(["id" => 4, 'code' => '63', 'name' => 'Булган']);
        AimagCity::create(["id" => 5, 'code' => '82', 'name' => 'Говь-Алтай']);
        AimagCity::create(["id" => 6, 'code' => '42', 'name' => 'Говьсүмбэр']);
        AimagCity::create(["id" => 7, 'code' => '11', 'name' => 'Улаанбаатар']);
        AimagCity::create(["id" => 8, 'code' => '45', 'name' => 'Дархан-Уул']);
        AimagCity::create(["id" => 9, 'code' => '44', 'name' => 'Дорноговь']);
        AimagCity::create(["id" => 10, 'code' => '21', 'name' => 'Дорнод']);
        AimagCity::create(["id" => 11, 'code' => '48', 'name' => 'Дундговь']);
        AimagCity::create(["id" => 12, 'code' => '81', 'name' => 'Завхан']);
        AimagCity::create(["id" => 13, 'code' => '61', 'name' => 'Орхон']);
        AimagCity::create(["id" => 14, 'code' => '62', 'name' => 'Өвөрхангай']);
        AimagCity::create(["id" => 15, 'code' => '46', 'name' => 'Өмнөговь']);
        AimagCity::create(["id" => 16, 'code' => '22', 'name' => 'Сүхбаатар']);
        AimagCity::create(["id" => 17, 'code' => '43', 'name' => 'Сэлэнгэ']);
        AimagCity::create(["id" => 18, 'code' => '41', 'name' => 'Төв']);
        AimagCity::create(["id" => 19, 'code' => '85', 'name' => 'Увс']);
        AimagCity::create(["id" => 20, 'code' => '84', 'name' => 'Ховд']);
        AimagCity::create(["id" => 21, 'code' => '67', 'name' => 'Хөвсгөл']);
        AimagCity::create(["id" => 22, 'code' => '23', 'name' => 'Хэнтий']);

        SoumDistrict::create(['id' => 158, 'code' => '04', "name" => 'Батцэнгэл', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 159, 'code' => '07', "name" => 'Булган', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 160, 'code' => '10', "name" => 'Жаргалант', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 161, 'code' => '13', "name" => 'Их Тамир', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 165, 'code' => '25', "name" => 'Тариат', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 286, 'code' => '28', "name" => 'Төвшрүүлэх', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 287, 'code' => '31', "name" => 'Хайрхан', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 288, 'code' => '34', "name" => 'Хангай', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 289, 'code' => '37', "name" => 'Хашаат', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 290, 'code' => '40', "name" => 'Хотонт', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 291, 'code' => '43', "name" => 'Цахир', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 292, 'code' => '46', "name" => 'Цэнхэр', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 293, 'code' => '49', "name" => 'Цэцэрлэг', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 294, 'code' => '52', "name" => 'Чулуут', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 157, 'code' => '01', "name" => 'Эрдэнэбулган', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 295, 'code' => '55', "name" => 'Эрдэнэмандал', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 162, 'code' => '16', "name" => 'Өгийнуур', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 163, 'code' => '19', "name" => 'Өлзийт', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 164, 'code' => '22', "name" => 'Өндөр-Улаан', 'aimag_city_id' => 1]);
        SoumDistrict::create(['id' => 297, 'code' => '04', "name" => 'Алтай', 'aimag_city_id' => 2]);
        SoumDistrict::create(['id' => 298, 'code' => '07', "name" => 'Алтанцөгц', 'aimag_city_id' => 2]);
        SoumDistrict::create(['id' => 299, 'code' => '10', "name" => 'Баяннуур', 'aimag_city_id' => 2]);
        SoumDistrict::create(['id' => 300, 'code' => '13', "name" => 'Бугат', 'aimag_city_id' => 2]);
        SoumDistrict::create(['id' => 301, 'code' => '16', "name" => 'Булган', 'aimag_city_id' => 2]);
        SoumDistrict::create(['id' => 302, 'code' => '19', "name" => 'Буянт', 'aimag_city_id' => 2]);
        SoumDistrict::create(['id' => 303, 'code' => '22', "name" => 'Дэлүүн', 'aimag_city_id' => 2]);
        SoumDistrict::create(['id' => 304, 'code' => '25', "name" => 'Ногооннуур', 'aimag_city_id' => 2]);
        SoumDistrict::create(['id' => 305, 'code' => '28', "name" => 'Сагсай', 'aimag_city_id' => 2]);
        SoumDistrict::create(['id' => 306, 'code' => '31', "name" => 'Толбо', 'aimag_city_id' => 2]);
        SoumDistrict::create(['id' => 307, 'code' => '34', "name" => 'Улаанхус', 'aimag_city_id' => 2]);
        SoumDistrict::create(['id' => 308, 'code' => '37', "name" => 'Цэнгэл', 'aimag_city_id' => 2]);
        SoumDistrict::create(['id' => 296, 'code' => '01', "name" => 'Өлгий', 'aimag_city_id' => 2]);
        SoumDistrict::create(['id' => 310, 'code' => '04', "name" => 'Баацагаан', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 314, 'code' => '16', "name" => 'Баян-Овоо', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 315, 'code' => '19', "name" => 'Баян-Өндөр', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 311, 'code' => '07', "name" => 'Баянбулаг', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 312, 'code' => '10', "name" => 'Баянговь', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 313, 'code' => '13', "name" => 'Баянлиг', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 309, 'code' => '01', "name" => 'Баянхонгор', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 316, 'code' => '22', "name" => 'Баянцагаан', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 317, 'code' => '25', "name" => 'Богд', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 319, 'code' => '31', "name" => 'Бууцагаан', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 318, 'code' => '28', "name" => 'Бөмбөгөр', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 320, 'code' => '34', "name" => 'Галуут', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 321, 'code' => '37', "name" => 'Гурванбулаг', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 322, 'code' => '40', "name" => 'Жаргалант', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 323, 'code' => '43', "name" => 'Жинст', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 324, 'code' => '46', "name" => 'Заг', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 326, 'code' => '52', "name" => 'Хүрээмарал', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 327, 'code' => '55', "name" => 'Шинэжинст', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 328, 'code' => '58', "name" => 'Эрдэнэцогт', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 325, 'code' => '49', "name" => 'Өлзийт', 'aimag_city_id' => 3]);
        SoumDistrict::create(['id' => 330, 'code' => '04', "name" => 'Баян-Агт', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 331, 'code' => '07', "name" => 'Баяннуур', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 332, 'code' => '10', "name" => 'Бугат', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 329, 'code' => '01', "name" => 'Булган', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 333, 'code' => '13', "name" => 'Бүрэгхангай', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 334, 'code' => '16', "name" => 'Гурван Булаг', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 335, 'code' => '19', "name" => 'Дашинчилэн', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 336, 'code' => '22', "name" => 'Могод', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 337, 'code' => '25', "name" => 'Орхон', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 338, 'code' => '28', "name" => 'Рашаант', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 166, 'code' => '31', "name" => 'Сайхан', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 167, 'code' => '34', "name" => 'Сэлэнгэ', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 168, 'code' => '37', "name" => 'Тэшиг', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 169, 'code' => '40', "name" => 'Хангал', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 170, 'code' => '43', "name" => 'Хишиг-Өндөр', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 171, 'code' => '46', "name" => 'Хутаг-Өндөр', 'aimag_city_id' => 4]);
        SoumDistrict::create(['id' => 173, 'code' => '04', "name" => 'Алтай', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 174, 'code' => '07', "name" => 'Баян-Уул', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 175, 'code' => '10', "name" => 'Бигэр', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 176, 'code' => '13', "name" => 'Бугат', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 177, 'code' => '16', "name" => 'Дарив', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 178, 'code' => '19', "name" => 'Дэлгэр', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 172, 'code' => '01', "name" => 'Есөнбулаг', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 179, 'code' => '22', "name" => 'Жаргалан', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 180, 'code' => '25', "name" => 'Тайшир', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 181, 'code' => '28', "name" => 'Тонхил', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 182, 'code' => '31', "name" => 'Төгрөг', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 183, 'code' => '34', "name" => 'Халиун', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 184, 'code' => '37', "name" => 'Хөхморьт', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 185, 'code' => '40', "name" => 'Цогт', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 186, 'code' => '43', "name" => 'Цээл', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 187, 'code' => '46', "name" => 'Чандмань', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 188, 'code' => '49', "name" => 'Шарга', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 189, 'code' => '52', "name" => 'Эрдэнэ', 'aimag_city_id' => 5]);
        SoumDistrict::create(['id' => 146, 'code' => '04', "name" => 'Баянтал', 'aimag_city_id' => 6]);
        SoumDistrict::create(['id' => 145, 'code' => '01', "name" => 'Сүмбэр', 'aimag_city_id' => 6]);
        SoumDistrict::create(['id' => 147, 'code' => '07', "name" => 'Шивээговь', 'aimag_city_id' => 6]);
        SoumDistrict::create(['id' => 148, 'code' => '01', "name" => 'Багануур', 'aimag_city_id' => 7]);
        SoumDistrict::create(['id' => 149, 'code' => '04', "name" => 'Багахангай', 'aimag_city_id' => 7]);
        SoumDistrict::create(['id' => 150, 'code' => '07', "name" => 'Баянгол', 'aimag_city_id' => 7]);
        SoumDistrict::create(['id' => 151, 'code' => '10', "name" => 'Баянзүрх', 'aimag_city_id' => 7]);
        SoumDistrict::create(['id' => 152, 'code' => '13', "name" => 'Налайх', 'aimag_city_id' => 7]);
        SoumDistrict::create(['id' => 153, 'code' => '16', "name" => 'Сонгинохайрхан', 'aimag_city_id' => 7]);
        SoumDistrict::create(['id' => 154, 'code' => '19', "name" => 'Сүхбаатар', 'aimag_city_id' => 7]);
        SoumDistrict::create(['id' => 155, 'code' => '22', "name" => 'Хан-Уул', 'aimag_city_id' => 7]);
        SoumDistrict::create(['id' => 156, 'code' => '25', "name" => 'Чингэлтэй', 'aimag_city_id' => 7]);
        SoumDistrict::create(['id' => 139, 'code' => '01', "name" => 'Дархан', 'aimag_city_id' => 8]);
        SoumDistrict::create(['id' => 140, 'code' => '04', "name" => 'Орхон', 'aimag_city_id' => 8]);
        SoumDistrict::create(['id' => 141, 'code' => '07', "name" => 'Хонгор', 'aimag_city_id' => 8]);
        SoumDistrict::create(['id' => 142, 'code' => '10', "name" => 'Шарын Гол', 'aimag_city_id' => 8]);
        SoumDistrict::create(['id' => 191, 'code' => '04', "name" => 'Айраг', 'aimag_city_id' => 9]);
        SoumDistrict::create(['id' => 192, 'code' => '07', "name" => 'Алтанширээ', 'aimag_city_id' => 9]);
        SoumDistrict::create(['id' => 193, 'code' => '10', "name" => 'Даланжаргалан', 'aimag_city_id' => 9]);
        SoumDistrict::create(['id' => 194, 'code' => '13', "name" => 'Дэлгэрэх', 'aimag_city_id' => 9]);
        SoumDistrict::create(['id' => 195, 'code' => '16', "name" => 'Замын-Үүд', 'aimag_city_id' => 9]);
        SoumDistrict::create(['id' => 196, 'code' => '19', "name" => 'Иххэт', 'aimag_city_id' => 9]);
        SoumDistrict::create(['id' => 197, 'code' => '22', "name" => 'Мандах', 'aimag_city_id' => 9]);
        SoumDistrict::create(['id' => 190, 'code' => '01', "name" => 'Сайншанд', 'aimag_city_id' => 9]);
        SoumDistrict::create(['id' => 199, 'code' => '28', "name" => 'Сайхандулаан', 'aimag_city_id' => 9]);
        SoumDistrict::create(['id' => 200, 'code' => '31', "name" => 'Улаанбадрах', 'aimag_city_id' => 9]);
        SoumDistrict::create(['id' => 201, 'code' => '34', "name" => 'Хатанбулаг', 'aimag_city_id' => 9]);
        SoumDistrict::create(['id' => 202, 'code' => '37', "name" => 'Хөвсгөл', 'aimag_city_id' => 9]);
        SoumDistrict::create(['id' => 203, 'code' => '40', "name" => 'Эрдэнэ', 'aimag_city_id' => 9]);
        SoumDistrict::create(['id' => 198, 'code' => '25', "name" => 'Өргөн', 'aimag_city_id' => 9]);
        SoumDistrict::create(['id' => 207, 'code' => '10', "name" => 'Баян-Уул', 'aimag_city_id' => 10]);
        SoumDistrict::create(['id' => 205, 'code' => '04', "name" => 'Баяндун', 'aimag_city_id' => 10]);
        SoumDistrict::create(['id' => 206, 'code' => '07', "name" => 'Баянтүмэн', 'aimag_city_id' => 10]);
        SoumDistrict::create(['id' => 208, 'code' => '13', "name" => 'Булган', 'aimag_city_id' => 10]);
        SoumDistrict::create(['id' => 209, 'code' => '16', "name" => 'Гурванзагал', 'aimag_city_id' => 10]);
        SoumDistrict::create(['id' => 210, 'code' => '19', "name" => 'Дашбалбар', 'aimag_city_id' => 10]);
        SoumDistrict::create(['id' => 211, 'code' => '22', "name" => 'Матад', 'aimag_city_id' => 10]);
        SoumDistrict::create(['id' => 212, 'code' => '25', "name" => 'Сэргэлэн', 'aimag_city_id' => 10]);
        SoumDistrict::create(['id' => 213, 'code' => '28', "name" => 'Халхгол', 'aimag_city_id' => 10]);
        SoumDistrict::create(['id' => 204, 'code' => '01', "name" => 'Хэрлэн', 'aimag_city_id' => 10]);
        SoumDistrict::create(['id' => 214, 'code' => '31', "name" => 'Хөлөнбуйр', 'aimag_city_id' => 10]);
        SoumDistrict::create(['id' => 215, 'code' => '34', "name" => 'Цагаан-Овоо', 'aimag_city_id' => 10]);
        SoumDistrict::create(['id' => 216, 'code' => '37', "name" => 'Чойбалсан', 'aimag_city_id' => 10]);
        SoumDistrict::create(['id' => 217, 'code' => '40', "name" => 'Чулуунхороот', 'aimag_city_id' => 10]);
        SoumDistrict::create(['id' => 219, 'code' => '04', "name" => 'Адаацаг', 'aimag_city_id' => 11]);
        SoumDistrict::create(['id' => 220, 'code' => '07', "name" => 'Баянжаргалан', 'aimag_city_id' => 11]);
        SoumDistrict::create(['id' => 221, 'code' => '10', "name" => 'Говь-Угтаал', 'aimag_city_id' => 11]);
        SoumDistrict::create(['id' => 222, 'code' => '13', "name" => 'Гурвансайхан', 'aimag_city_id' => 11]);
        SoumDistrict::create(['id' => 223, 'code' => '16', "name" => 'Дэлгэрхангай', 'aimag_city_id' => 11]);
        SoumDistrict::create(['id' => 224, 'code' => '19', "name" => 'Дэлгэрцогт', 'aimag_city_id' => 11]);
        SoumDistrict::create(['id' => 225, 'code' => '22', "name" => 'Дэрэн', 'aimag_city_id' => 11]);
        SoumDistrict::create(['id' => 226, 'code' => '25', "name" => 'Луус', 'aimag_city_id' => 11]);
        SoumDistrict::create(['id' => 218, 'code' => '01', "name" => 'Сайнцагаан', 'aimag_city_id' => 11]);
        SoumDistrict::create(['id' => 229, 'code' => '34', "name" => 'Сайхан-Овоо', 'aimag_city_id' => 11]);
        SoumDistrict::create(['id' => 230, 'code' => '37', "name" => 'Хулд', 'aimag_city_id' => 11]);
        SoumDistrict::create(['id' => 231, 'code' => '40', "name" => 'Цагаандэлгэр', 'aimag_city_id' => 11]);
        SoumDistrict::create(['id' => 232, 'code' => '43', "name" => 'Эрдэнэдалай', 'aimag_city_id' => 11]);
        SoumDistrict::create(['id' => 227, 'code' => '28', "name" => 'Өлзийт', 'aimag_city_id' => 11]);
        SoumDistrict::create(['id' => 228, 'code' => '31', "name" => 'Өндөршил', 'aimag_city_id' => 11]);
        SoumDistrict::create(['id' => 234, 'code' => '04', "name" => 'Алдархаан', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 235, 'code' => '07', "name" => 'Асгат', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 236, 'code' => '10', "name" => 'Баянтэс', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 237, 'code' => '13', "name" => 'Баянхайрхан', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 238, 'code' => '16', "name" => 'Дөрвөлжин', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 239, 'code' => '19', "name" => 'Завханмандал', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 240, 'code' => '22', "name" => 'Идэр', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 241, 'code' => '25', "name" => 'Их-Уул', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 242, 'code' => '28', "name" => 'Нөмрөг', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 243, 'code' => '31', "name" => 'Отгон', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 244, 'code' => '34', "name" => 'Сантмаргац', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 245, 'code' => '37', "name" => 'Сонгино', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 246, 'code' => '40', "name" => 'Тосонцэнгэл', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 248, 'code' => '46', "name" => 'Тэлмэн', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 249, 'code' => '49', "name" => 'Тэс', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 247, 'code' => '43', "name" => 'Түдэвтэй', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 233, 'code' => '01', "name" => 'Улиастай', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 250, 'code' => '52', "name" => 'Ургамал', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 251, 'code' => '55', "name" => 'Цагаанхайрхан', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 252, 'code' => '58', "name" => 'Цагаанчулуут', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 253, 'code' => '61', "name" => 'Цэцэн-Уул', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 254, 'code' => '64', "name" => 'Шилүүстэй', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 255, 'code' => '67', "name" => 'Эрдэнэхайрхан', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 256, 'code' => '70', "name" => 'Яруу', 'aimag_city_id' => 12]);
        SoumDistrict::create(['id' => 143, 'code' => '01', "name" => 'Баян-Өндөр', 'aimag_city_id' => 13]);
        SoumDistrict::create(['id' => 144, 'code' => '04', "name" => 'Жаргалант', 'aimag_city_id' => 13]);
        SoumDistrict::create(['id' => 257, 'code' => '01', "name" => 'Арвайхээр', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 258, 'code' => '04', "name" => 'Баруунбаян-Улаан', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 259, 'code' => '07', "name" => 'Бат-Өлзий', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 261, 'code' => '13', "name" => 'Баян-Өндөр', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 260, 'code' => '10', "name" => 'Баянгол', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 262, 'code' => '16', "name" => 'Богд', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 263, 'code' => '19', "name" => 'Бүрд', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 264, 'code' => '22', "name" => 'Гучин-Ус', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 265, 'code' => '25', "name" => 'Есөн Зүйл', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 266, 'code' => '28', "name" => 'Зүүнбаян-Улаан', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 267, 'code' => '31', "name" => 'Нарийнтээл', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 269, 'code' => '37', "name" => 'Сант', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 270, 'code' => '40', "name" => 'Тарагт', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 271, 'code' => '43', "name" => 'Төгрөг', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 272, 'code' => '46', "name" => 'Уянга', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 273, 'code' => '49', "name" => 'Хайрхандулаан', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 274, 'code' => '52', "name" => 'Хархорин', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 275, 'code' => '55', "name" => 'Хужирт', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 268, 'code' => '34', "name" => 'Өлзийт', 'aimag_city_id' => 14]);
        SoumDistrict::create(['id' => 278, 'code' => '07', "name" => 'Баян-Овоо', 'aimag_city_id' => 15]);
        SoumDistrict::create(['id' => 277, 'code' => '04', "name" => 'Баяндалай', 'aimag_city_id' => 15]);
        SoumDistrict::create(['id' => 279, 'code' => '10', "name" => 'Булган', 'aimag_city_id' => 15]);
        SoumDistrict::create(['id' => 280, 'code' => '13', "name" => 'Гурвантэс', 'aimag_city_id' => 15]);
        SoumDistrict::create(['id' => 276, 'code' => '01', "name" => 'Даланзадгад', 'aimag_city_id' => 15]);
        SoumDistrict::create(['id' => 281, 'code' => '16', "name" => 'Мандал-Овоо', 'aimag_city_id' => 15]);
        SoumDistrict::create(['id' => 282, 'code' => '19', "name" => 'Манлай', 'aimag_city_id' => 15]);
        SoumDistrict::create(['id' => 284, 'code' => '25', "name" => 'Номгон', 'aimag_city_id' => 15]);
        SoumDistrict::create(['id' => 283, 'code' => '22', "name" => 'Ноён', 'aimag_city_id' => 15]);
        SoumDistrict::create(['id' => 285, 'code' => '28', "name" => 'Сэврэй', 'aimag_city_id' => 15]);
        SoumDistrict::create(['id' => 1, 'code' => '31', "name" => 'Ханбогд', 'aimag_city_id' => 15]);
        SoumDistrict::create(['id' => 2, 'code' => '34', "name" => 'Ханхонгор', 'aimag_city_id' => 15]);
        SoumDistrict::create(['id' => 3, 'code' => '37', "name" => 'Хүрмэн', 'aimag_city_id' => 15]);
        SoumDistrict::create(['id' => 4, 'code' => '40', "name" => 'Цогт-Овоо', 'aimag_city_id' => 15]);
        SoumDistrict::create(['id' => 5, 'code' => '43', "name" => 'Цогтцэций', 'aimag_city_id' => 15]);
        SoumDistrict::create(['id' => 7, 'code' => '04', "name" => 'Асгат', 'aimag_city_id' => 16]);
        SoumDistrict::create(['id' => 6, 'code' => '01', "name" => 'Баруун-Урт', 'aimag_city_id' => 16]);
        SoumDistrict::create(['id' => 8, 'code' => '07', "name" => 'Баяндэлгэр', 'aimag_city_id' => 16]);
        SoumDistrict::create(['id' => 9, 'code' => '10', "name" => 'Дарьганга', 'aimag_city_id' => 16]);
        SoumDistrict::create(['id' => 10, 'code' => '13', "name" => 'Мөнххаан', 'aimag_city_id' => 16]);
        SoumDistrict::create(['id' => 11, 'code' => '16', "name" => 'Наран', 'aimag_city_id' => 16]);
        SoumDistrict::create(['id' => 12, 'code' => '19', "name" => 'Онгон', 'aimag_city_id' => 16]);
        SoumDistrict::create(['id' => 13, 'code' => '22', "name" => 'Сүхбаатар', 'aimag_city_id' => 16]);
        SoumDistrict::create(['id' => 14, 'code' => '25', "name" => 'Түвшинширээ', 'aimag_city_id' => 16]);
        SoumDistrict::create(['id' => 15, 'code' => '28', "name" => 'Түмэнцогт', 'aimag_city_id' => 16]);
        SoumDistrict::create(['id' => 16, 'code' => '31', "name" => 'Уулбаян', 'aimag_city_id' => 16]);
        SoumDistrict::create(['id' => 17, 'code' => '34', "name" => 'Халзан', 'aimag_city_id' => 16]);
        SoumDistrict::create(['id' => 18, 'code' => '37', "name" => 'Эрдэнэцагаан', 'aimag_city_id' => 16]);
        SoumDistrict::create(['id' => 20, 'code' => '04', "name" => 'Алтанбулаг', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 21, 'code' => '07', "name" => 'Баруунбүрэн', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 22, 'code' => '10', "name" => 'Баянгол', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 23, 'code' => '13', "name" => 'Ерөө', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 24, 'code' => '16', "name" => 'Жавхлант', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 25, 'code' => '19', "name" => 'Зүүнбүрэн', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 26, 'code' => '22', "name" => 'Мандал', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 27, 'code' => '25', "name" => 'Орхон', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 28, 'code' => '28', "name" => 'Орхонтуул', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 29, 'code' => '31', "name" => 'Сайхан', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 30, 'code' => '34', "name" => 'Сант', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 19, 'code' => '01', "name" => 'Сүхбаатар', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 31, 'code' => '37', "name" => 'Түшиг', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 33, 'code' => '43', "name" => 'Хушаат', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 32, 'code' => '40', "name" => 'Хүдэр', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 34, 'code' => '46', "name" => 'Цагааннуур', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 35, 'code' => '49', "name" => 'Шаамар', 'aimag_city_id' => 17]);
        SoumDistrict::create(['id' => 37, 'code' => '04', "name" => 'Алтанбулаг', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 38, 'code' => '07', "name" => 'Аргалант', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 39, 'code' => '10', "name" => 'Архуст', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 40, 'code' => '13', "name" => 'Батсүмбэр', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 41, 'code' => '16', "name" => 'Баян', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 44, 'code' => '25', "name" => 'Баян-Өнжүүл', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 42, 'code' => '19', "name" => 'Баяндэлгэр', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 43, 'code' => '22', "name" => 'Баянжаргалан', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 45, 'code' => '28', "name" => 'Баянхангай', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 46, 'code' => '31', "name" => 'Баянцагаан', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 47, 'code' => '34', "name" => 'Баянцогт', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 48, 'code' => '37', "name" => 'Баянчандмань', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 49, 'code' => '40', "name" => 'Борнуур', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 50, 'code' => '43', "name" => 'Бүрэн', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 51, 'code' => '46', "name" => 'Дэлгэрхаан', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 52, 'code' => '49', "name" => 'Жаргалант', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 53, 'code' => '52', "name" => 'Заамар', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 36, 'code' => '01', "name" => 'Зуунмод', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 54, 'code' => '55', "name" => 'Лүн', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 55, 'code' => '58', "name" => 'Мөнгөнморьт', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 58, 'code' => '67', "name" => 'Сэргэлэн', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 57, 'code' => '64', "name" => 'Сүмбэр', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 59, 'code' => '70', "name" => 'Угтаалцайдам', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 60, 'code' => '73', "name" => 'Цээл', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 61, 'code' => '76', "name" => 'Эрдэнэ', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 62, 'code' => '79', "name" => 'Эрдэнэсант', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 56, 'code' => '61', "name" => 'Өндөрширээт', 'aimag_city_id' => 18]);
        SoumDistrict::create(['id' => 64, 'code' => '04', "name" => 'Баруунтуруун', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 65, 'code' => '07', "name" => 'Бөхмөрөн', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 66, 'code' => '10', "name" => 'Давст', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 67, 'code' => '13', "name" => 'Завхан', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 68, 'code' => '16', "name" => 'Зүүнговь', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 69, 'code' => '19', "name" => 'Зүүнхангай', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 70, 'code' => '22', "name" => 'Малчин', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 71, 'code' => '25', "name" => 'Наранбулаг', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 75, 'code' => '37', "name" => 'Сагил', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 76, 'code' => '40', "name" => 'Тариалан', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 78, 'code' => '46', "name" => 'Тэс', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 77, 'code' => '43', "name" => 'Түргэн', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 63, 'code' => '01', "name" => 'Улаангом', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 79, 'code' => '49', "name" => 'Ховд', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 80, 'code' => '52', "name" => 'Хяргас', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 81, 'code' => '55', "name" => 'Цагаанхайрхан', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 72, 'code' => '28', "name" => 'Өлгий', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 73, 'code' => '31', "name" => 'Өмнөговь', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 74, 'code' => '34', "name" => 'Өндөрхангай', 'aimag_city_id' => 19]);
        SoumDistrict::create(['id' => 83, 'code' => '04', "name" => 'Алтай', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 84, 'code' => '07', "name" => 'Булган', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 85, 'code' => '10', "name" => 'Буянт', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 86, 'code' => '13', "name" => 'Дарви', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 88, 'code' => '19', "name" => 'Дуут', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 87, 'code' => '16', "name" => 'Дөргөн', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 82, 'code' => '01', "name" => 'Жаргалант', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 89, 'code' => '22', "name" => 'Зэрэг', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 90, 'code' => '25', "name" => 'Манхан', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 93, 'code' => '34', "name" => 'Мянгад', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 91, 'code' => '28', "name" => 'Мөнххайрхан', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 92, 'code' => '31', "name" => 'Мөст', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 95, 'code' => '40', "name" => 'Ховд', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 96, 'code' => '43', "name" => 'Цэцэг', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 97, 'code' => '46', "name" => 'Чандмань', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 98, 'code' => '49', "name" => 'Эрдэнэбүрэн', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 94, 'code' => '37', "name" => 'Үенч', 'aimag_city_id' => 20]);
        SoumDistrict::create(['id' => 100, 'code' => '04', "name" => 'Алаг-Эрдэнэ', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 101, 'code' => '07', "name" => 'Арбулаг', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 102, 'code' => '10', "name" => 'Баянзүрх', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 103, 'code' => '13', "name" => 'Бүрэнтогтох', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 104, 'code' => '16', "name" => 'Галт', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 105, 'code' => '19', "name" => 'Жаргалант', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 106, 'code' => '22', "name" => 'Их-Уул', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 99, 'code' => '01', "name" => 'Мөрөн', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 107, 'code' => '25', "name" => 'Рашаант', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 108, 'code' => '28', "name" => 'Рэнчинлхүмбэ', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 109, 'code' => '31', "name" => 'Тариалан', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 110, 'code' => '34', "name" => 'Тосонцэнгэл', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 112, 'code' => '40', "name" => 'Түнэл', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 111, 'code' => '37', "name" => 'Төмөрбулаг', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 113, 'code' => '43', "name" => 'Улаан-Уул', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 114, 'code' => '46', "name" => 'Ханх', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 116, 'code' => '52', "name" => 'Цагаан-Уул', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 117, 'code' => '55', "name" => 'Цагаан-Үүр', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 115, 'code' => '49', "name" => 'Цагааннуур', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 118, 'code' => '58', "name" => 'Цэцэрлэг', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 119, 'code' => '61', "name" => 'Чандмань-Өндөр', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 120, 'code' => '64', "name" => 'Шинэ-Идэр', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 121, 'code' => '67', "name" => 'Эрдэнэбулган', 'aimag_city_id' => 21]);
        SoumDistrict::create(['id' => 123, 'code' => '04', "name" => 'Батноров', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 124, 'code' => '07', "name" => 'Батширээт', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 125, 'code' => '10', "name" => 'Баян-Адарга', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 127, 'code' => '16', "name" => 'Баян-Овоо', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 126, 'code' => '13', "name" => 'Баянмөнх', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 128, 'code' => '19', "name" => 'Баянхутаг', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 129, 'code' => '22', "name" => 'Биндэр', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 341, 'code' => '52', "name" => 'Бор-Өндөр', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 130, 'code' => '25', "name" => 'Галшар', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 131, 'code' => '28', "name" => 'Дадал', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 132, 'code' => '31', "name" => 'Дархан', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 133, 'code' => '34', "name" => 'Дэлгэрхаан', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 134, 'code' => '37', "name" => 'Жаргалтхаан', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 135, 'code' => '40', "name" => 'Мөрөн', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 136, 'code' => '43', "name" => 'Норовлин', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 122, 'code' => '01', "name" => 'Хэрлэн', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 138, 'code' => '49', "name" => 'Цэнхэрмандал', 'aimag_city_id' => 22]);
        SoumDistrict::create(['id' => 137, 'code' => '46', "name" => 'Өмнөдэлгэр', 'aimag_city_id' => 22]);
    }
}
