// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAChRTzngj_dbz-XttiaIQN2m1fkrv12XM',
    appId: '1:759328300749:web:c9dfa2e2ce16b10a7b1384',
    messagingSenderId: '759328300749',
    projectId: 'waste-project-49d6d',
    authDomain: 'waste-project-49d6d.firebaseapp.com',
    storageBucket: 'waste-project-49d6d.firebasestorage.app',
    measurementId: 'G-YZ4C0PNRFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkylGaklNKJARA5ATwP3LWzOuucYMszcA',
    appId: '1:759328300749:android:6209f07f7fc303787b1384',
    messagingSenderId: '759328300749',
    projectId: 'waste-project-49d6d',
    storageBucket: 'waste-project-49d6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmMz7SxrmcXYaZZ00mmcqsHyimYWIJP8M',
    appId: '1:759328300749:ios:deed5dd3225466ab7b1384',
    messagingSenderId: '759328300749',
    projectId: 'waste-project-49d6d',
    storageBucket: 'waste-project-49d6d.firebasestorage.app',
    iosBundleId: 'com.example.wasteMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmMz7SxrmcXYaZZ00mmcqsHyimYWIJP8M',
    appId: '1:759328300749:ios:deed5dd3225466ab7b1384',
    messagingSenderId: '759328300749',
    projectId: 'waste-project-49d6d',
    storageBucket: 'waste-project-49d6d.firebasestorage.app',
    iosBundleId: 'com.example.wasteMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAChRTzngj_dbz-XttiaIQN2m1fkrv12XM',
    appId: '1:759328300749:web:845cd9ccaf85a8bc7b1384',
    messagingSenderId: '759328300749',
    projectId: 'waste-project-49d6d',
    authDomain: 'waste-project-49d6d.firebaseapp.com',
    storageBucket: 'waste-project-49d6d.firebasestorage.app',
    measurementId: 'G-L1ZCSKEH3K',
  );
}
