// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9q7d3mPcI63DTUyXjIjsGo61n3Iz3eLM',
    appId: '1:759328300749:web:193ac8945a7c6ee27b1384',
    messagingSenderId: '759328300749',
    projectId: 'waste-project-49d6d',
    authDomain: 'waste-project-49d6d.firebaseapp.com',
    storageBucket: 'waste-project-49d6d.appspot.com',
    measurementId: 'G-3MEWKD2GBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW_Q7wU4Ir6CXBhJhZpVNBC63sJg2neN8',
    appId: '1:759328300749:android:fd7b7934ef14004c7b1384',
    messagingSenderId: '759328300749',
    projectId: 'waste-project-49d6d',
    storageBucket: 'waste-project-49d6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpZRNAIMy02TkDbEZLcubSW9aTTWKN-Sg',
    appId: '1:759328300749:ios:21d47e9114a855dd7b1384',
    messagingSenderId: '759328300749',
    projectId: 'waste-project-49d6d',
    storageBucket: 'waste-project-49d6d.appspot.com',
    iosClientId:
        '759328300749-teaevt9o2if8ju2bg0dsj2179ta9629k.apps.googleusercontent.com',
    iosBundleId: 'mn.lancers.wasteMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpZRNAIMy02TkDbEZLcubSW9aTTWKN-Sg',
    appId: '1:759328300749:ios:21d47e9114a855dd7b1384',
    messagingSenderId: '759328300749',
    projectId: 'waste-project-49d6d',
    storageBucket: 'waste-project-49d6d.appspot.com',
    iosClientId:
        '759328300749-teaevt9o2if8ju2bg0dsj2179ta9629k.apps.googleusercontent.com',
    iosBundleId: 'mn.lancers.wasteMobile',
  );
}
